In [1]:
import pandas as pd
import numpy as np

DATA_PATH = "../data/raw/indian_roads_dataset.csv"

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (20000, 24)

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10

In [2]:
print("========== DATASET OVERVIEW ==========")

print("\nShape:")
print(df.shape)

print("\nColumn Names:")
for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nUnique Values:")
print(df.nunique())

print("\nDataset Info:")
df.info()

========== DATASET OVERVIEW ==========

Shape:
(20000, 24)

Column Names:
1. accident_id
2. city
3. state
4. latitude
5. longitude
6. date
7. time
8. hour
9. day_of_week
10. is_weekend
11. road_type
12. lanes
13. traffic_signal
14. weather
15. visibility
16. temperature
17. traffic_density
18. cause
19. accident_severity
20. vehicles_involved
21. casualties
22. is_peak_hour
23. festival
24. risk_score

Data Types:
accident_id            int64
city                     str
state                    str
latitude             float64
longitude            float64
date                     str
time                     str
hour                   int64
day_of_week              str
is_weekend             int64
road_type                str
lanes                  int64
traffic_signal         int64
weather                  str
visibility               str
temperature            int64
traffic_density          str
cause                    str
accident_severity        str
vehicles_involved      int64
casualties             int64
is_peak_hour           int64
festival                 str
risk_score           float64
dtype: object

Missing Values:
accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64

Duplicate Rows:
0

Unique Values:
accident_id          20000
city                     8
state                    7
latitude             19907
longitude            19927
date                  1201
time                    24
hour                    24
day_of_week              7
is_weekend               2
road_type                3
lanes                    6
traffic_signal           2
weather                  3
visibility               3
temperature             26
traffic_density          3
cause                    5
accident_severity        3
vehicles_involved        5
casualties               6
is_peak_hour             2
festival                 4
risk_score              18
dtype: int64

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int64
 1   city               20000 non-null  str
 2   state              20000 non-null  str
 3   latitude           20000 non-null  float64
 4   longitude          20000 non-null  float64
 5   date               20000 non-null  str
 6   time               20000 non-null  str
 7   hour               20000 non-null  int64
 8   day_of_week        20000 non-null  str
 9   is_weekend         20000 non-null  int64
 10  road_type          20000 non-null  str
 11  lanes              20000 non-null  int64
 12  traffic_signal     20000 non-null  int64
 13  weather            20000 non-null  str
 14  visibility         20000 non-null  str
 15  temperature        20000 non-null  int64
 16  traffic_density    20000 non-null  str
 17  cause              20000 non-null  str
 18  accident_severity  20000 non-null  str
 19  vehicles_involved  20000 non-null  int64
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  int64
 22  festival           115 non-null    str
 23  risk_score         20000 non-null  float64
dtypes: float64(3), int64(9), str(12)
memory usage: 3.7 MB

In [3]:
print("========== NUMERICAL SUMMARY ==========")
display(df.describe(include="all").T)

========== NUMERICAL SUMMARY ==========

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
accident_id,20000.0,NaN,NaN,NaN,9999.5,5773.647028,0.0,4999.75,9999.5,14999.25,19999.0
city,20000,8,Chandigarh,2577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,20000,7,Maharashtra,5009,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,20000.0,NaN,NaN,NaN,20.389207,6.165791,12.800172,13.198653,18.812008,28.402467,30.79996
longitude,20000.0,NaN,NaN,NaN,78.17333,4.485967,72.700017,73.997979,77.297,80.111089,88.499861
date,20000,1201,2022-11-03,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
time,20000,24,2:00,888,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hour,20000.0,NaN,NaN,NaN,11.4872,6.945563,0.0,5.0,12.0,18.0,23.0
day_of_week,20000,7,Monday,2966,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_weekend,20000.0,NaN,NaN,NaN,0.28615,0.451972,0.0,0.0,0.0,1.0,1.0
road_type,20000,3,urban,6745,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lanes,20000.0,NaN,NaN,NaN,3.49395,1.705406,1.0,2.0,4.0,5.0,6.0
traffic_signal,20000.0,NaN,NaN,NaN,0.49985,0.500012,0.0,0.0,0.0,1.0,1.0
weather,20000,3,clear,6690,NaN,NaN,NaN,NaN,NaN,NaN,NaN
visibility,20000,3,low,9987,NaN,NaN,NaN,NaN,NaN,NaN,NaN
temperature,20000.0,NaN,NaN,NaN,27.5796,7.454746,15.0,21.0,28.0,34.0,40.0
traffic_density,20000,3,low,7067,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cause,20000,5,distraction,4026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
accident_severity,20000,3,minor,11025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
vehicles_involved,20000.0,NaN,NaN,NaN,2.992,1.415534,1.0,2.0,3.0,4.0,5.0
casualties,20000.0,NaN,NaN,NaN,1.72645,1.489104,0.0,1.0,1.0,3.0,5.0
is_peak_hour,20000.0,NaN,NaN,NaN,0.2474,0.431512,0.0,0.0,0.0,0.0,1.0
festival,115,4,Holi,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
risk_score,20000.0,NaN,NaN,NaN,0.437585,0.21813,0.1,0.25,0.45,0.6,1.0

In [4]:
categorical_columns = [
    "city",
    "state",
    "day_of_week",
    "road_type",
    "traffic_signal",
    "weather",
    "visibility",
    "traffic_density",
    "cause",
    "accident_severity",
    "is_weekend",
    "is_peak_hour",
    "festival"
]

for col in categorical_columns:
    print(f"\n========== {col.upper()} ==========")
    print(df[col].value_counts(dropna=False))

========== CITY ==========
city
Chandigarh    2577
Chennai       2575
Kolkata       2559
Pune          2517
Mumbai        2492
Bangalore     2438
Delhi         2433
Hyderabad     2409
Name: count, dtype: int64

========== STATE ==========
state
Maharashtra    5009
Punjab         2577
Tamil Nadu     2575
West Bengal    2559
Karnataka      2438
Delhi          2433
Telangana      2409
Name: count, dtype: int64

========== DAY_OF_WEEK ==========
day_of_week
Monday       2966
Friday       2879
Tuesday      2871
Saturday     2867
Sunday       2856
Thursday     2835
Wednesday    2726
Name: count, dtype: int64

========== ROAD_TYPE ==========
road_type
urban      6745
rural      6639
highway    6616
Name: count, dtype: int64

========== TRAFFIC_SIGNAL ==========
traffic_signal
0    10003
1     9997
Name: count, dtype: int64

========== WEATHER ==========
weather
clear    6690
rain     6677
fog      6633
Name: count, dtype: int64

========== VISIBILITY ==========
visibility
low       9987
high      6690
medium    3323
Name: count, dtype: int64

========== TRAFFIC_DENSITY ==========
traffic_density
low       7067
high      7034
medium    5899
Name: count, dtype: int64

========== CAUSE ==========
cause
distraction      4026
overspeeding     4025
weather          3997
drunk driving    3978
poor road        3974
Name: count, dtype: int64

========== ACCIDENT_SEVERITY ==========
accident_severity
minor    11025
major     5988
fatal     2987
Name: count, dtype: int64

========== IS_WEEKEND ==========
is_weekend
0    14277
1     5723
Name: count, dtype: int64

========== IS_PEAK_HOUR ==========
is_peak_hour
0    15052
1     4948
Name: count, dtype: int64

========== FESTIVAL ==========
festival
NaN         19885
Holi           38
Eid            34
Diwali         31
New Year       12
Name: count, dtype: int64

In [5]:
print("========== CITY DISTRIBUTION ==========")

city_counts = df["city"].value_counts()

print(city_counts)

print("\nPercentage:")
print((city_counts / len(df) * 100).round(2))

========== CITY DISTRIBUTION ==========
city
Chandigarh    2577
Chennai       2575
Kolkata       2559
Pune          2517
Mumbai        2492
Bangalore     2438
Delhi         2433
Hyderabad     2409
Name: count, dtype: int64

Percentage:
city
Chandigarh    12.88
Chennai       12.88
Kolkata       12.80
Pune          12.58
Mumbai        12.46
Bangalore     12.19
Delhi         12.16
Hyderabad     12.04
Name: count, dtype: float64

In [6]:
print("========== CITY-STATE RELATIONSHIP ==========")

city_state = pd.crosstab(df["city"], df["state"])

display(city_state)

========== CITY-STATE RELATIONSHIP ==========

state,Delhi,Karnataka,Maharashtra,Punjab,Tamil Nadu,Telangana,West Bengal
city,,,,,,,
Bangalore,0,2438,0,0,0,0,0
Chandigarh,0,0,0,2577,0,0,0
Chennai,0,0,0,0,2575,0,0
Delhi,2433,0,0,0,0,0,0
Hyderabad,0,0,0,0,0,2409,0
Kolkata,0,0,0,0,0,0,2559
Mumbai,0,0,2492,0,0,0,0
Pune,0,0,2517,0,0,0,0

In [7]:
print("========== GEOGRAPHIC DISTRIBUTION BY CITY ==========")

geo_summary = df.groupby("city").agg(
    records=("accident_id", "count"),
    min_latitude=("latitude", "min"),
    max_latitude=("latitude", "max"),
    min_longitude=("longitude", "min"),
    max_longitude=("longitude", "max"),
    avg_latitude=("latitude", "mean"),
    avg_longitude=("longitude", "mean")
)

display(geo_summary)

========== GEOGRAPHIC DISTRIBUTION BY CITY ==========

,records,min_latitude,max_latitude,min_longitude,max_longitude,avg_latitude,avg_longitude
city,,,,,,,
Bangalore,2438,12.800400,13.199728,77.400094,77.800000,12.999878,77.600004
Chandigarh,2577,30.600092,30.799960,76.700078,76.899965,30.698616,76.801333
Chennai,2575,12.800172,13.199589,80.100004,80.299948,13.001594,80.200036
Delhi,2433,28.400436,28.899794,76.800054,77.299829,28.651106,77.045334
Hyderabad,2409,17.200361,17.599974,78.200010,78.599896,17.400494,78.402883
Kolkata,2559,22.400074,22.699902,88.200049,88.499861,22.550071,88.353031
Mumbai,2492,18.800049,19.299950,72.700017,72.999973,19.051718,72.848928
Pune,2517,18.400006,18.699837,73.700352,73.999971,18.550879,73.852559

In [8]:
print("========== RISK SCORE VALUES ==========")

risk_values = df["risk_score"].value_counts().sort_index()

display(risk_values)

print("\nNumber of unique risk scores:", df["risk_score"].nunique())

========== RISK SCORE VALUES ==========

risk_score
0.10    3149
0.20      12
0.25    2111
0.30    1664
0.35       7
0.40     269
0.45    6421
0.50     212
0.55      41
0.60    1304
0.65    2740
0.70       6
0.75      19
0.80    1508
0.85     298
0.90      11
0.95       1
1.00     227
Name: count, dtype: int64

Number of unique risk scores: 18

In [9]:
print("========== RISK SCORE BY SEVERITY ==========")

display(
    df.groupby("accident_severity")["risk_score"]
      .agg(["count", "min", "mean", "median", "max"])
)

========== RISK SCORE BY SEVERITY ==========

                   count  min      mean  median  max
accident_severity
fatal               2987  0.3  0.607516    0.65  1.0
major               5988  0.1  0.406847    0.45  0.9
minor              11025  0.1  0.408240    0.45  0.9

In [10]:
print("========== RISK SCORE RELATIONSHIPS ==========")

risk_relationships = df.groupby(
    ["accident_severity", "traffic_density"]
)["risk_score"].agg(["count", "mean", "min", "max"])

display(risk_relationships)

========== RISK SCORE RELATIONSHIPS ==========

                                   count      mean  min  max
accident_severity traffic_density
fatal             high              1045  0.763445  0.5  1.0
                  low               1061  0.509095  0.3  0.8
                  medium             881  0.541090  0.3  0.8
major             high              2077  0.565094  0.3  0.9
                  low               2116  0.308979  0.1  0.6
                  medium            1795  0.339109  0.1  0.7
minor             high              3912  0.565440  0.3  0.9
                  low               3890  0.309602  0.1  0.6
                  medium            3223  0.336488  0.1  0.7

In [11]:
print("========== RISK SCORE VS IMPORTANT VARIABLES ==========")

numeric_cols = [
    "hour",
    "lanes",
    "traffic_signal",
    "temperature",
    "vehicles_involved",
    "casualties",
    "is_peak_hour",
    "risk_score"
]

display(df[numeric_cols].corr(numeric_only=True)["risk_score"].sort_values(ascending=False))

========== RISK SCORE VS IMPORTANT VARIABLES ==========

risk_score           1.000000
is_peak_hour         0.436848
hour                 0.122017
casualties           0.119954
traffic_signal       0.001817
vehicles_involved    0.000642
lanes               -0.001721
temperature         -0.001885
Name: risk_score, dtype: float64

In [12]:
print("========== RISK SCORE BY CITY ==========")

display(
    df.groupby("city")["risk_score"]
      .agg(["count", "mean", "min", "max"])
      .sort_values("mean", ascending=False)
)

========== RISK SCORE BY CITY ==========

            count      mean  min  max
city
Chandigarh   2577  0.441618  0.1  1.0
Bangalore    2438  0.440217  0.1  1.0
Hyderabad    2409  0.439456  0.1  1.0
Chennai      2575  0.437573  0.1  1.0
Delhi        2433  0.437115  0.1  1.0
Pune         2517  0.435836  0.1  1.0
Kolkata      2559  0.434584  0.1  1.0
Mumbai       2492  0.434350  0.1  1.0

In [13]:
print("========== DUPLICATE FEATURE COMBINATIONS ==========")

feature_cols = [
    "city",
    "road_type",
    "lanes",
    "traffic_signal",
    "weather",
    "visibility",
    "traffic_density",
    "cause",
    "accident_severity",
    "vehicles_involved",
    "casualties",
    "is_peak_hour"
]

risk_consistency = (
    df.groupby(feature_cols)["risk_score"]
      .nunique()
)

print("Feature combinations with multiple risk scores:",
      (risk_consistency > 1).sum())

print("Total unique feature combinations:",
      len(risk_consistency))

========== DUPLICATE FEATURE COMBINATIONS ==========
Feature combinations with multiple risk scores: 3
Total unique feature combinations: 19744

In [14]:
print("========== COORDINATE ANALYSIS ==========")

print("Unique latitude:", df["latitude"].nunique())
print("Unique longitude:", df["longitude"].nunique())

print(
    "Exact latitude-longitude pairs:",
    df[["latitude", "longitude"]].drop_duplicates().shape[0]
)

========== COORDINATE ANALYSIS ==========
Unique latitude: 19907
Unique longitude: 19927
Exact latitude-longitude pairs: 20000

In [15]:
print("========== DATE RANGE ==========")

date_series = pd.to_datetime(df["date"], errors="coerce")

print("Minimum date:", date_series.min())
print("Maximum date:", date_series.max())
print("Invalid dates:", date_series.isna().sum())

========== DATE RANGE ==========
Minimum date: 2022-01-01 00:00:00
Maximum date: 2025-04-15 00:00:00
Invalid dates: 0

In [16]:
print("========== RISK SCORE BY CATEGORICAL FEATURES ==========")

categorical_features = [
    "road_type",
    "weather",
    "visibility",
    "traffic_density",
    "cause",
    "accident_severity",
    "is_peak_hour",
    "is_weekend"
]

for col in categorical_features:
    print(f"\n--- {col} ---")
    result = (
        df.groupby(col)["risk_score"]
        .agg(["count", "mean", "median", "min", "max"])
        .sort_values("mean", ascending=False)
    )
    display(result)

========== RISK SCORE BY CATEGORICAL FEATURES ==========

--- road_type ---

           count      mean  median  min  max
road_type
urban       6745  0.440593    0.45  0.1  1.0
highway     6616  0.437455    0.45  0.1  1.0
rural       6639  0.434659    0.45  0.1  1.0

--- weather ---

         count      mean  median   min   max
weather
fog       6633  0.589123    0.60  0.45  1.00
rain      6677  0.488146    0.45  0.25  1.00
clear     6690  0.236876    0.25  0.10  0.75

--- visibility ---

            count      mean  median   min   max
visibility
low          9987  0.589176    0.60  0.45  1.00
medium       3323  0.386067    0.40  0.25  0.80
high         6690  0.236876    0.25  0.10  0.75

--- traffic_density ---

                 count      mean  median  min  max
traffic_density
high              7034  0.594754    0.65  0.3  1.0
medium            5899  0.367842    0.45  0.1  0.8
low               7067  0.339366    0.45  0.1  0.8

--- cause ---

               count      mean  median  min  max
cause
overspeeding    4025  0.440186    0.45  0.1  1.0
poor road       3974  0.439796    0.45  0.1  1.0
weather         3997  0.439742    0.45  0.1  1.0
drunk driving   3978  0.438964    0.45  0.1  1.0
distraction     4026  0.429297    0.45  0.1  1.0

--- accident_severity ---

                   count      mean  median  min  max
accident_severity
fatal               2987  0.607516    0.65  0.3  1.0
minor              11025  0.408240    0.45  0.1  0.9
major               5988  0.406847    0.45  0.1  0.9

--- is_peak_hour ---

              count      mean  median   min   max
is_peak_hour
1              4948  0.603779    0.60  0.25  1.00
0             15052  0.382952    0.45  0.10  0.95

--- is_weekend ---

            count      mean  median  min  max
is_weekend
1            5723  0.438974    0.45  0.1  1.0
0           14277  0.437028    0.45  0.1  1.0

In [17]:
print("========== RISK SCORE BY SEVERITY + TRAFFIC + PEAK HOUR ==========")

result = (
    df.groupby(
        ["accident_severity", "traffic_density", "is_peak_hour"]
    )["risk_score"]
    .agg(["count", "mean", "median", "min", "max"])
    .reset_index()
)

display(result)

========== RISK SCORE BY SEVERITY + TRAFFIC + PEAK HOUR ==========

,accident_severity,traffic_density,is_peak_hour,count,mean,median,min,max
0,fatal,high,0,604,0.697185,0.70,0.50,0.95
1,fatal,high,1,441,0.854195,1.00,0.65,1.00
2,fatal,low,0,984,0.499187,0.45,0.30,0.75
3,fatal,low,1,77,0.635714,0.60,0.45,0.80
4,fatal,medium,0,659,0.505994,0.65,0.30,0.65
5,fatal,medium,1,222,0.645270,0.60,0.45,0.80
6,major,high,0,1180,0.497331,0.45,0.30,0.75
7,major,high,1,897,0.654236,0.80,0.45,0.90
8,major,low,0,1981,0.299293,0.25,0.10,0.55
9,major,low,1,135,0.451111,0.60,0.25,0.60
10,major,medium,0,1322,0.300000,0.25,0.10,0.55
11,major,medium,1,473,0.448414,0.60,0.25,0.70
12,minor,high,0,2259,0.500863,0.45,0.30,0.75
13,minor,high,1,1653,0.653690,0.80,0.45,0.90
14,minor,low,0,3637,0.298790,0.25,0.10,0.55
15,minor,low,1,253,0.465020,0.60,0.25,0.60
16,minor,medium,0,2426,0.298413,0.25,0.10,0.55
17,minor,medium,1,797,0.452384,0.60,0.25,0.70

In [18]:
print("========== RISK SCORE DISTRIBUTION ==========")

display(
    df["risk_score"]
    .value_counts()
    .sort_index()
    .to_frame("count")
)

print("\nMean:", df["risk_score"].mean())
print("Median:", df["risk_score"].median())
print("Standard deviation:", df["risk_score"].std())

========== RISK SCORE DISTRIBUTION ==========

            count
risk_score
0.10         3149
0.20           12
0.25         2111
0.30         1664
0.35            7
0.40          269
0.45         6421
0.50          212
0.55           41
0.60         1304
0.65         2740
0.70            6
0.75           19
0.80         1508
0.85          298
0.90           11
0.95            1
1.00          227

Mean: 0.43758500000000006
Median: 0.45
Standard deviation: 0.21812954132771653

In [20]:
risk_values = sorted(df["risk_score"].unique())

print("Risk score values:")
print(risk_values)

print("\nDifferences between consecutive values:")
print(np.diff(risk_values))

Risk score values:
[np.float64(0.1), np.float64(0.2), np.float64(0.25), np.float64(0.3), np.float64(0.35), np.float64(0.4), np.float64(0.45), np.float64(0.5), np.float64(0.55), np.float64(0.6), np.float64(0.65), np.float64(0.7), np.float64(0.75), np.float64(0.8), np.float64(0.85), np.float64(0.9), np.float64(0.95), np.float64(1.0)]

Differences between consecutive values:
[0.1  0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05
 0.05 0.05 0.05]

In [21]:
print("========== WEATHER VS VISIBILITY ==========")

weather_visibility = pd.crosstab(
    df["weather"],
    df["visibility"],
    normalize="index"
) * 100

display(weather_visibility.round(2))

========== WEATHER VS VISIBILITY ==========

visibility   high     low  medium
weather
clear       100.0    0.00    0.00
fog           0.0  100.00    0.00
rain          0.0   50.23   49.77

In [22]:
print("========== TIME FIELD CONSISTENCY ==========")

date_check = pd.to_datetime(df["date"], errors="coerce")

calculated_day = date_check.dt.day_name()
calculated_weekend = calculated_day.isin(["Saturday", "Sunday"]).astype(int)

print("Day-of-week mismatches:",
      (calculated_day != df["day_of_week"]).sum())

print("Weekend mismatches:",
      (calculated_weekend != df["is_weekend"]).sum())

print("\nHour/time mismatches:")

calculated_hour = pd.to_datetime(
    df["time"],
    format="%H:%M",
    errors="coerce"
).dt.hour

print((calculated_hour != df["hour"]).sum())

========== TIME FIELD CONSISTENCY ==========
Day-of-week mismatches: 0
Weekend mismatches: 0

Hour/time mismatches:
0

In [23]:
print("========== PEAK HOUR PATTERN ==========")

display(
    pd.crosstab(
        df["hour"],
        df["is_peak_hour"],
        normalize="index"
    ).round(2)
)

========== PEAK HOUR PATTERN ==========

is_peak_hour    0    1
hour
0             1.0  0.0
1             1.0  0.0
2             1.0  0.0
3             1.0  0.0
4             1.0  0.0
5             1.0  0.0
6             1.0  0.0
7             1.0  0.0
8             0.0  1.0
9             0.0  1.0
10            0.0  1.0
11            1.0  0.0
12            1.0  0.0
13            1.0  0.0
14            1.0  0.0
15            1.0  0.0
16            1.0  0.0
17            0.0  1.0
18            0.0  1.0
19            0.0  1.0
20            1.0  0.0
21            1.0  0.0
22            1.0  0.0
23            1.0  0.0

In [24]:
print("========== CITY COORDINATE RANGES ==========")

geo_summary = df.groupby("city").agg(
    records=("accident_id", "count"),
    min_lat=("latitude", "min"),
    max_lat=("latitude", "max"),
    min_lon=("longitude", "min"),
    max_lon=("longitude", "max"),
    mean_lat=("latitude", "mean"),
    mean_lon=("longitude", "mean")
)

display(geo_summary)

========== CITY COORDINATE RANGES ==========

,records,min_lat,max_lat,min_lon,max_lon,mean_lat,mean_lon
city,,,,,,,
Bangalore,2438,12.800400,13.199728,77.400094,77.800000,12.999878,77.600004
Chandigarh,2577,30.600092,30.799960,76.700078,76.899965,30.698616,76.801333
Chennai,2575,12.800172,13.199589,80.100004,80.299948,13.001594,80.200036
Delhi,2433,28.400436,28.899794,76.800054,77.299829,28.651106,77.045334
Hyderabad,2409,17.200361,17.599974,78.200010,78.599896,17.400494,78.402883
Kolkata,2559,22.400074,22.699902,88.200049,88.499861,22.550071,88.353031
Mumbai,2492,18.800049,19.299950,72.700017,72.999973,19.051718,72.848928
Pune,2517,18.400006,18.699837,73.700352,73.999971,18.550879,73.852559

In [25]:
print("========== RISK SCORE VALUES ==========")

risk_values = sorted(df["risk_score"].unique())

print("Number of unique values:", len(risk_values))
print("Values:", risk_values)

print("\nDifferences:")
print(np.diff(risk_values))

========== RISK SCORE VALUES ==========
Number of unique values: 18
Values: [np.float64(0.1), np.float64(0.2), np.float64(0.25), np.float64(0.3), np.float64(0.35), np.float64(0.4), np.float64(0.45), np.float64(0.5), np.float64(0.55), np.float64(0.6), np.float64(0.65), np.float64(0.7), np.float64(0.75), np.float64(0.8), np.float64(0.85), np.float64(0.9), np.float64(0.95), np.float64(1.0)]

Differences:
[0.1  0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05
 0.05 0.05 0.05]

In [26]:
print("========== RISK SCORE BY CORE CONDITIONS ==========")

core_analysis = (
    df.groupby(
        [
            "weather",
            "traffic_density",
            "is_peak_hour",
            "accident_severity"
        ]
    )["risk_score"]
    .agg(["count", "mean", "min", "max"])
    .reset_index()
)

display(core_analysis)

========== RISK SCORE BY CORE CONDITIONS ==========

,weather,traffic_density,is_peak_hour,accident_severity,count,mean,min,max
0,clear,high,0,fatal,212,0.500472,0.50,0.60
1,clear,high,0,major,405,0.300494,0.30,0.40
2,clear,high,0,minor,744,0.300941,0.30,0.40
3,clear,high,1,fatal,144,0.650694,0.65,0.75
4,clear,high,1,major,291,0.450344,0.45,0.55
5,clear,high,1,minor,545,0.450367,0.45,0.55
6,clear,low,0,fatal,326,0.301227,0.30,0.40
7,clear,low,0,major,671,0.100000,0.10,0.10
8,clear,low,0,minor,1235,0.100324,0.10,0.20
9,clear,low,1,fatal,29,0.453448,0.45,0.55
10,clear,low,1,major,48,0.250000,0.25,0.25
11,clear,low,1,minor,81,0.250000,0.25,0.25
12,clear,medium,0,fatal,204,0.300980,0.30,0.40
13,clear,medium,0,major,438,0.100685,0.10,0.20
14,clear,medium,0,minor,817,0.100612,0.10,0.20
15,clear,medium,1,fatal,77,0.451299,0.45,0.55
16,clear,medium,1,major,164,0.250000,0.25,0.25
17,clear,medium,1,minor,259,0.250000,0.25,0.25
18,fog,high,0,fatal,186,0.850000,0.85,0.85
19,fog,high,0,major,390,0.650769,0.65,0.75
20,fog,high,0,minor,731,0.650684,0.65,0.75
21,fog,high,1,fatal,158,1.000000,1.00,1.00
22,fog,high,1,major,299,0.801003,0.80,0.90
23,fog,high,1,minor,564,0.800532,0.80,0.90
24,fog,low,0,fatal,319,0.650940,0.65,0.75
25,fog,low,0,major,660,0.450909,0.45,0.55
26,fog,low,0,minor,1198,0.450584,0.45,0.55
27,fog,low,1,fatal,23,0.800000,0.80,0.80
28,fog,low,1,major,52,0.600000,0.60,0.60
29,fog,low,1,minor,88,0.600000,0.60,0.60
30,fog,medium,0,fatal,229,0.650000,0.65,0.65
31,fog,medium,0,major,421,0.451188,0.45,0.55
32,fog,medium,0,minor,805,0.450497,0.45,0.55
33,fog,medium,1,fatal,80,0.800000,0.80,0.80
34,fog,medium,1,major,153,0.600000,0.60,0.60
35,fog,medium,1,minor,277,0.600722,0.60,0.70
36,rain,high,0,fatal,206,0.761650,0.65,0.95
37,rain,high,0,major,385,0.548961,0.45,0.65
38,rain,high,0,minor,784,0.550893,0.45,0.75
39,rain,high,1,fatal,139,0.899281,0.80,1.00
40,rain,high,1,major,307,0.704560,0.60,0.90
41,rain,high,1,minor,544,0.705147,0.60,0.90
42,rain,low,0,fatal,339,0.546755,0.45,0.75
43,rain,low,0,major,650,0.351077,0.25,0.55
44,rain,low,0,minor,1204,0.351329,0.25,0.55
45,rain,low,1,fatal,25,0.696000,0.60,0.80
46,rain,low,1,major,35,0.505714,0.40,0.60
47,rain,low,1,minor,84,0.530952,0.40,0.60
48,rain,medium,0,fatal,226,0.545133,0.45,0.65
49,rain,medium,0,major,463,0.351080,0.25,0.45
50,rain,medium,0,minor,804,0.347139,0.25,0.55
51,rain,medium,1,fatal,65,0.684615,0.60,0.80
52,rain,medium,1,major,156,0.508333,0.40,0.70
53,rain,medium,1,minor,261,0.495785,0.40,0.70